### ISSUE TITLE
go-chi/chi current version is 5.0.7 (2021-11-18)

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-indexer#100]
is there a reason why we're using v1.5.4 rather than v5.0.7?  v1.5.4 is 2021-02-27.

https://github.com/oasisprotocol/oasis-indexer/blob/5b0b5a7888df3e6db1ecae9485c2f00285af46ab/go.mod#L7

**Comment by aefhm** [comment]
Nope, moved to `v5.0.7`.
