### ISSUE TITLE
api: Add current Oasis Node block status

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/oasis-indexer#102]
##### SUMMARY

We want to be able to see the latest height reached by an Oasis Node.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

This can be probably cached because this should be a commonly hit endpoint.

**Comment by Yawning** [comment]
Doesn't the empty query (that returns chain id, latest block, and latest update) handle this?

**Comment by aefhm** [comment]
> Doesn't the empty query (that returns chain id, latest block, and latest update) handle this?

By empty query (`https://index.oasislabs.com/v1/`), the returned value is the latest block indexed not the latest block height on the Oasis Node.

**Comment by Yawning** [comment]
Maybe an indexer health endpoint, that indicates health if the delta between the oasis node height and the last indexed height is "small".

**Comment by aefhm** [comment]
Yeah, @ennsharma suggested that may be a common enough case that this is the same situation as what you mentioned about latest height state that warrants in memory caching. We thought it would be a nice to have if the API layer got access to this state from the analyzer.

**Comment by mitjat** [comment]
Options:
1) a separate mini container (for robustness) that polls the node and puts max height in the indexer db
2) do not expose max height; tell people/frontends to use [the production timestamp](https://github.com/oasisprotocol/oasis-indexer/blob/0c9b204ca4a4e75c37e10bd56413a2e7e55572e5/api/spec/v1.yaml#L808-L808) of newest indexed block to detect drift
3) do not expose max height; tell people/frontends to hit a separate endpoint instead to obtain max height

For now, go with 2 and just rename `latest_update` field in https://index.oasislabs.com/v1/ or its docstring for clarity.
