### ISSUE TITLE
tests/genesis: Sample random subset of addresses to validate.

### ISSUE THREAD

**Issue by ennsharma** [oasisprotocol/oasis-indexer#111]
##### SUMMARY
The genesis state test takes a long time to run (~5-10m), primarily bottlenecked by validating every account in the staking backend has the correct balance. This problem will get unwieldy soon as the number of accounts continues to increase, we start needing to validate paratime accounts, etc.

We should modify this test to more generically select a (configurable size) random sample of accounts (or other primitives) and validate them

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`tests`

**Comment by mitjat** [comment]
It's called "genesis state", but really it just means asking the node to give a snapshot of balances _at a certain abitrary height_. See [API](https://pkg.go.dev/github.com/oasisprotocol/oasis-core/go/consensus/api#ClientBackend).

It is too expensive to ask the node for that. Instead, choose a few addresses and ask the node for the balance of each of them in turn.

This test is currently disabled in CI/prod, but you can run it locally.

**Comment by mitjat** [comment]
Alternatively: Keep the test as-is, but run it not too frequently. E.g. daily or weekly or just after a release. Depends on how long the "genesis" dump takes.
