### ISSUE TITLE
use math/big to calculate balances

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/oasis-indexer#113]
Use [`Quantity`](https://github.com/oasislabs/oasis-core/blob/531421a928dc3450abd721c832d376549626a473/go/common/quantity/quantity.go#L28-L28). Not just for calculations, but even just for internally transferring values that contain balances (which can be >2^64)

**Comment by mitjat** [comment]
https://app.clickup.com/t/3t22v98
