### ISSUE TITLE
Better error handling for malformed addresses and params

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/oasis-indexer#117]
##### SUMMARY

We probably want to check URL params on query endpoints or at least improve the error messages.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

API

**Comment by mitjat** [comment]
@Andrew7234 will this be covered by the work you're currently doing around early parsing of URL params?

**Comment by Andrew7234** [comment]
Yup!

**Comment by Andrew7234** [comment]
Closed by #112
