### ISSUE TITLE
analyzer: Improve perf by indexing certain keys

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/oasis-indexer#118]
##### ISSUE TYPE
- Bug Report

##### STEPS TO REPRODUCE
https://github.com/oasisprotocol/oasis-indexer/issues/86#issuecomment-1182278867

##### ACTUAL RESULTS

```paste below

```

**Comment by aefhm** [comment]
Relates to #121

**Comment by mitjat** [comment]
I assume this was completed to the extent that we covered the immediate needs. More DB tuning will remain an ongoing task. Existing Grafana charts should alert us to underperforming queries.
