### ISSUE TITLE
Searching transactions by some senders is timeouting

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-indexer#121]
https://index.oasislabs.com/v1/consensus/transactions?sender=oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90
is timeouting  Error 524

_Originally posted by @lukaw3d in https://github.com/oasisprotocol/oasis-indexer/issues/86#issuecomment-1182278867_

**Comment by ennsharma** [comment]
[This](https://github.com/oasisprotocol/oasis-indexer/blob/main/storage/migrations/0006_oasis_3_tx_sender_ix.sql) should have fixed it.

**Comment by lukaw3d** [comment]
:+1:
