### ISSUE TITLE
api: add GetLatestBlock endpoint

### ISSUE THREAD

**Issue by Andrew7234** [oasisprotocol/oasis-indexer#135]
We expect most indexer queries to be for the latest block data. Currently, clients must fetch the `/status` to get the latest index block number, and then fetch it from `/consensus/blocks/{height}`. Although clients can keep track of the current indexed block number, It could be nicer to directly expose a `/consensus/blocks/latest` endpoint, or even expose a websocket stream that pushes the latest block data.

**Comment by ennsharma** [comment]
I realized this is actually unnecessary after the fix in https://github.com/oasisprotocol/oasis-indexer/pull/136 goes in. You can achieve this by doing `/consensus/blocks?limit=k` to get the `k` latest blocks. Not opposed to having the endpoint anyway for aesthetic reasons if you feel super strongly.

**Comment by aefhm** [comment]
We decided not to do this.
