### ISSUE TITLE
Indexer regularly times out when writing to DB

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/oasis-indexer#144]
Almost exactly every 70 seconds, the following error entry appears in the logs of prod indexer:
```
{"error":"timeout: context deadline exceeded", "level":"error", "module":"postgres", "msg":"failed to execute tx batch"}
```

Find and remove the reason.

**Comment by mitjat** [comment]
I happened to notice some raw prometheus metrics for DB latencies:
```
consensus_main_damask_db_operations{database="postgres",operation="aggregate_stats",status="failure"} 493                                                                                     
consensus_main_damask_db_operations{database="postgres",operation="process_block_consensus",status="failure"} 2                                                                               
consensus_main_damask_db_operations{database="postgres",operation="process_block_consensus",status="success"} 11050
```

There is no `operation="aggregate_stats",status="success"`. So it looks like `aggregate_stats` is consistently timing out.

**Comment by ennsharma** [comment]
Ah! This is a good catch -- `aggregate_stats` is really just a utility and runs in it's own goroutine. It worked locally, but we hadn't cut a new officially indexer release since https://github.com/oasisprotocol/oasis-indexer/pull/132 was merged, I guess some configuration error in the nonlocal deployment.

**Comment by mitjat** [comment]
Since the timeout repeats every 70 seconds, I'm pretty sure it's [this explicit timeout of 60s](https://github.com/oasisprotocol/oasis-indexer/blob/mitjat%2Fsmall-fixes/analyzer/consensus/workers.go#L24) + the 10s delay between retries. I guess our DB just grew to the point where 60s is not enough.

Who uses the `/stats/{tps,daily_volume}` endpoints? If they're just nice-to-have at this point, we could remove the 5-minute stats, and run the daily stats without too much concern for complexity (for now).

**Comment by mitjat** [comment]
**Task:** Easy solution for now: Calculate this once a day, increase timeouts.

If we do it once a day, maybe there's less value to the 5min granularity report. But let's leave it in there for smoother graphs, and maybe BD still finds it valuable.
