### ISSUE TITLE
Link token transfers with tx_ids

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/oasis-indexer#146]
We currently index paratime-level token transfers (in Emerald, and in the future in any paratime using the `accounts` SDK module) by parsing events emitted by the node. The event object contains only the semantics of the token transfer (to, from, amount), but not the tx id where the transfer happened. So we're not able to link the transfer back to the originating tx.

Fix this by doing one of the two:
- Expand the event object so include the tx hash. This will involve several lib layers in runtime-client and client-sdk. [This low-level object](https://github.com/oasislabs/oasis-core/blob/531421a928dc3450abd721c832d376549626a473/go/runtime/client/api/api.go#L144-L144) still contains the tx hash, but [are discarded in `client-sdk`](https://github.com/oasisprotocol/oasis-sdk/blob/dd2b3716a6536b8e779285b9cc99b2c9d8d0a31e/client-sdk/go/client/client.go#L353-L353)
- Parse the token transfers from the tx body directly, rather than from events. I don't know how easy/hard that is. It is preferable for performance.

**Comment by pro-wh** [comment]
imo expand event object to include the tx hash (nullable)

parsing token transfers from tx body---we'll do that too, but we'll have failed txs and stuff, so it would be nice to keep the events for queries of only transfers that happened

**Comment by mitjat** [comment]
This works for Emerald partially: We parse events to know that the recipient was associated with the tx (`associated_accounts` table), but we do not technically know that they were the recipient. For that we'd need to parse the tx body (or pipe the tx id thru the events-related functions, as described above).

For consensus, we don't have anything yet.

p2 because this is primarily important for the Explorer, where Emerald is the higher priority.

**Comment by mitjat** [comment]
In consensus, we're now adding this functionality in #123 

For Emerald, what we currently have (`emerald_related_transactions` table) might be enough. Let's reopen/revisit if it turns out to not be exact enough. IIUC that will only happen when we have 2+ emerald transfers with the same sender and receiver in a single round.

If we do need to add more tracking: For consistency with consensus, and also to speed things up (so we don't [fetch events from the node for every sdk module](https://github.com/oasisprotocol/oasis-indexer/blob/305095e8b1c04916924b517eeca4405d97586a90/analyzer/modules/accounts.go#L32-L32) separately), could we just use the [output of the existing `GetTransactionsWithResults` call](https://github.com/oasisprotocol/oasis-indexer/blob/305095e8b1c04916924b517eeca4405d97586a90/storage/oasis/consensus.go#L78-L78)?
