### ISSUE TITLE
Design doc: dealing with node and paratime versions

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/oasis-indexer#161]
Some stuff to consider:
- new version of the consensus protocol is released
- new version of the paratime is released
- how do we parse genesis? It will contain mostly balances that we already arrived at as part of oasis-3 (and we have transactions to substantiate the balances, so we don't want to throw away that history and say "account `A` has balance `X` because genesis says so), but there _might_ be balance adjustments in the genesis (e.g. a hard fork to deal with fraud).
- how do we migrate tables. Is there only ever one version of tables (e.g. when oasis-4.* tables are created, we migrate oasis-3.* into them and delete oasis-3)? Likely yes.
- how do we maintain analyzers that can talk to old nodes and parse old chains? Go doesn't allow us to include multiple versions of the same lib (we'd need `oasis-core` and/or `client-sdk`). Should the oasis-2 analyzer be a separate git branch? We can test, deploy etc all the non-current (= obsolete or upcoming) versions much more manually and that's fine, but how do we backport fixes and how do we reindex if needed?
- how do we run a full reindex of the current chain? Maybe we won't support that any more (without fully reindexing from block 0 and dealing with all the version migrations/transitions).

**Comment by gw0** [comment]
>     * how do we parse genesis? It will contain mostly balances that we already arrived at as part of oasis-3 (and we have transactions to substantiate the balances, so we don't want to throw away that history and say "account `A` has balance `X` because genesis says so), but there _might_ be balance adjustments in the genesis (e.g. a hard fork to deal with fraud).

Although drastically inefficient, instead of parsing the genesis file you can also also iterate over all non-zero accounts at any specific block height.

**Comment by mitjat** [comment]
Continuing in an internal doc, see clickup. TLDR:
- We'll use a single DB schema (`oasis-3`).
- We'll worry about runtime versioning later; it is largely independent.
- `main` branch should be able to talk to all node versions, otherwise the process of reindexing everything is too manual and unpredictable. One option is to create proxies that covert node output to a set of consistent, indexer-internal types.
