### ISSUE TITLE
Fix tracking of escrow slashing

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/oasis-indexer#192]
(This investigation into how the indexer tracks escrowed tokens came from https://github.com/oasisprotocol/oasis-indexer/issues/179#issuecomment-1279686551.)

The indexer tracks escrow balances (and shares) by observing events. Most of these events can be processed in an order-independent manner, but one update query currently cannot. The query is executed when we observe the `TakeEscrowEvent`, i.e. slashing of escrowed tokens:
https://github.com/oasisprotocol/oasis-indexer/blob/4aa5a529147586a1316c2c5f25dd7ccc56e1ac58/analyzer/queries.go#L207-L211

It appears that the query has several issues. Note that the `$2` in that query is the [`Amount` in `TakeEscrowEvent`](https://github.com/oasislabs/oasis-core/blob/531421a928dc3450abd721c832d376549626a473/docs/consensus/services/staking.md#L660-L660) documented as "the amount (in base units) taken (= slashed)".

Questions to make sure we fix this correctly:

1) [The query we're discussing](https://github.com/oasisprotocol/oasis-indexer/blob/4aa5a529147586a1316c2c5f25dd7ccc56e1ac58/analyzer/queries.go#L209-L209) grabs this amount field, performs shares-derivation math on it, and then updates the `balance` (!) fields. Is this buggy, and it should be updating `escrow_total_shares_*` to the value that it currently computes?
2) Should that same query additionally be updating the balances by setting `UPDATE ... SET escrow_balance_active -= {{.Take.Amount}}, escrow_balance_debonding -= {{.Take.Amount}}`?
3) Is that same query buggy in a separate way in that it subtracts `$2` from both `*_active` _and_ `*_debonding`? The [oasis-core implementation](https://github.com/oasislabs/oasis-core/blob/531421a928dc3450abd721c832d376549626a473/go/consensus/tendermint/apps/staking/state/state.go#L746-L752) seems to take/slash as much as possible from the active escrow, and if there's not enough money there, then it takes the remainder from the debonding escrow. If so, I guess that `TakeEscrowEvent` should be reporting `ActiveAmount` and `DebondingAmount` separately, rather than reporting their sum in a single `Amount` field?
4) It's super hacky that we're reproducing the oasis-core quotient math (converting amounts/balances to shares) in the indexer. [All other escrow-related events](https://github.com/oasislabs/oasis-core/blob/531421a928dc3450abd721c832d376549626a473/go/staking/api/api.go#L265-L320) except `TakeEscrowEvent` (aka slash) include `Amount` and `Shares` fields, and shares are derived from amount (or vice versa) on the node. Should `TakeEscrowEvent` be expanded with `LostActiveShares` and `LostDebondingShares` fields?
5) Higher-level Q: I assume that the number of shares is not meaningful without knowing how many shares there are in the pool. Do we keep track of the total number of shares in each pool anywhere in the indexer? (I assume we'll want to expose them in the GUI)

**Comment by pro-wh** [comment]
> updating escrow_total_shares_*

slashing doesn't change the shares

> -= {{.Take.Amount}}

if the amount is available, that'll be better than computing it on the database

> seems to take/slash as much as possible from the active escrow, and if there's not enough money there, then it takes the remainder from the debonding escrow

I'm reading that differently, where it slashes the same proportion from both active and debonding

> Should TakeEscrowEvent be expanded with LostActiveShares and LostDebondingShares fields

agreed on it being better not for indexer to have to reproduce math, but slashing doesn't change shares so

**Comment by mitjat** [comment]
Thanks, I re-read the code. We slash the active and debonding pools proportionally, yes. We are also careful to not slash more than is available, of course.

Example 1: an account has 100 ROSE in active escrow and 300 ROSE in debonding escrow, and gets slashed by 40 ROSE. 10 ROSE will be slashed from active escrow, and 30 ROSE from debonding. The `Take` event will have `Amount=40`.
Example 2: an account has 100 ROSE in active escrow and 300 ROSE in debonding escrow, and gets slashed by 1000 ROSE. 100 ROSE will be slashed from active escrow, and 300 ROSE from debonding. The `Take` event will have `Amount=400`.

A problem is that the 10 and the 30 (from example 1 above) cannot be derived from the event data (= 40) without knowing the balances in active and debonding escrow at the time the event was generated.

When the indexer processes blocks sequentially (as it currently does), we do have that information, and the current query seems _almost_ correct:
- :heavy_check_mark: we don't need to worry about negative balances (= slashing more than is available in escrow), because the event reports the actual amount slashed, not the amount we wanted to slash
- :x: we should use `FLOOR`, not `ROUND`, because that's what happens in oasis-core

Ideally, the event itself would contain separate fields for the amount slashed from active vs debonding escrow. I'm asking on slack if oasis-core is open to that.

**Comment by aefhm** [comment]
Sounds good to me. Thanks!

**Comment by mitjat** [comment]
Created https://github.com/oasisprotocol/oasis-core/pull/5016 (and associated https://github.com/oasisprotocol/oasis-sdk/pull/1188) to introduce the extra field to the slash event emitted by oasis-core.

**Comment by mitjat** [comment]
(Hopefully) resolved by #210. We can revisit once https://github.com/oasisprotocol/oasis-core/pull/5016 is widely deployed on mainnet, and use the new field ... but even then, the field won't magically appear for old events. So probably the cleanest and easiest thing to only start using the new field on the post-Damask blockchain.
