### ISSUE TITLE
analyzer/consensus: insert on "events" violates FK constraint

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/oasis-indexer#195]
Consensus analyzer sometimes creates INSERT statements for the `events` table that violates foreign key constraints

Sample error at height 8493489:
```
    "err": "ERROR: insert or update on table \"events\" violates foreign key constraint \"events_txn_block_txn_hash_txn_index_fkey\" (SQLSTATE 23503)",
    "sql": "\n\t\tINSERT INTO oasis_3.events (backend, type, body, txn_block, txn_hash, txn_index)\n\t\t\tVALUES ($1, $2, $3, $4, $5, $6)",
    "args": [
      "roothash",
      "ExecutorCommitted",
      "{\"commit\":{\"node_id\":\"hpsco0ffTxzXgY4qd22Q/p/lSPYEmGvYMzwVyUK2Tx (truncated 635 bytes)",
      8493489,
      "fa67b2079d5dfce288200d86778306fd740e4d4eb5c60fdbda797aa8f879d321",
      2
    ],
```

See [full list](https://cloudlogging.app.goo.gl/2jFefJoxwXUiR5Yy9) of errors. Each error is logged three times, at three different layers. A little spammy but each layer has separate useful information ...

**Notes:**
- We shouldn't be producing invalid references.
- Notice how the reference is to a tx from the same height. So it's probably just that the event should be inserted after the tx, or (better) we should be using deferrable constraints as described in https://github.com/oasisprotocol/oasis-indexer/issues/50
- The problem is, the block is retried _and succeeds_ on second try. Does that mean we're not inserting all queries relating to a block inside a db transaction? If we were, the db transaction would fail, no data would be written to the db, and the retry should fail in the exact same way. Ohhh ... maybe there's a race between the events analyzer and the txs analyzer, and it depends which adds its sql statements first.

**Comment by aefhm** [comment]
I think this is soft addressed by constraint removal in https://github.com/oasisprotocol/oasis-indexer/pull/188

**Comment by pro-wh** [comment]
what was the constraint?

**Comment by aefhm** [comment]
> what was the constraint?

https://github.com/oasisprotocol/oasis-indexer/blob/2687d24573c36306b125ea179ddc26e3453671a8/storage/migrations/01_oasis_3_consensus.up.sql#L63

**Comment by pro-wh** [comment]
do we use different goroutines to enqueue the queries for the tx and the events?
