### ISSUE TITLE
Track runtime (un)suspensions

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/oasis-indexer#238]
Runtimes can be (un)suspended during their lifetime. The indexer used to track their status; as of #232, that's no longer the case. Should we want to start tracking the suspended status of runtimes again, we'll proably want to do something more efficient than just reverting #232. Some options:

1. My first thought was to keep the Registry().GetRuntimes() call from https://github.com/oasisprotocol/oasis-indexer/pull/232/files but patch its implementation so it includes the `Suspended` flag in its description of runtimes.

2. Jernej suggests we fetch the roothash block for the runtime; when a runtime is suspended, it emits a block with a special `HeaderType=Suspended`. Example of how we'd do it from `storage/oasis/oasis.go`:
```go
import (
	roothashAPI "github.com/oasisprotocol/oasis-core/go/roothash/api"
	roothashBlock "github.com/oasisprotocol/oasis-core/go/roothash/api/block"
)
...
rhBlock, err := cc.client.RootHash().GetLatestBlock(ctx, &roothashAPI.RuntimeRequest{RuntimeID: ..., Height: ...})
if block.Header.HeaderType == roothashBlock.Suspended {
	# Runtime was suspended in round block.Header.Round
}
```

3. Yawning suggests patching consensus so it emits a new special event when a runtime is (un)suspended.

**Comment by kostko** [comment]
I only suggest 2 if you need to work with current versions and you need to process roothash finalization events anyway (not sure if you are doing that at the moment). For upcoming versions emitting a special event (e.g. option 3) is the best one.

**Comment by mitjat** [comment]
The prerequisite for option 3 (= dedicated events on paratime (un)suspension) has now been implemented in https://github.com/oasisprotocol/oasis-core/pull/5088 :tada: 
So we should go down that route. It will be a while before it's released though.
