### ISSUE TITLE
Deploy with CORS enabled

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-indexer#249]
Frontend currently can't use the deployed API, so I had to add a dev proxy: https://github.com/oasisprotocol/explorer-frontend/pull/5/commits/f355c7c012935c2cd8d1a8e0b721cda1c4e064b4.

CORS headers in oasisscan https://api.oasisscan.com/mainnet/validator/list?pageSize=500
```
access-control-allow-credentials: true
access-control-allow-headers: DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type
access-control-allow-methods: GET, POST, OPTIONS
access-control-allow-origin: *
```

and oasismonitor https://monitor.oasis.dev/data/transactions?limit=20
```
access-control-allow-credentials: true
access-control-allow-origin: *
```

**Comment by lukaw3d** [comment]
https://github.com/oasisprotocol/explorer/issues/19

**Comment by mitjat** [comment]
not deployed yet, but merged into `main`. to be deployed probably by the end of the week.
