### ISSUE TITLE
Implement /emerald/events endpoint

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/oasis-indexer#258]
Like #357 but for emerald/runtimes. Here, we don't have openapi yet either. So the tasks are:
- capture+parse data from blockchain
- create DB schema, write to DB
- create openapi spec, implement API endpoints

Also consider the "Emerald vs EVM" section in [this Explorer MVP feedback doc](https://docs.google.com/document/d/1lhxpVDBJUfcxodBw0aMiS4eNk2Ma_YSdyO5JgiFUoQs/edit?disco=AAAAmS9WMbY): Perhaps we want to flatten/unify EVM events and Emerald events.

**Comment by Andrew7234** [comment]
Closed by https://github.com/oasisprotocol/oasis-indexer/pull/301/ and https://github.com/oasisprotocol/oasis-indexer/pull/295
