### ISSUE TITLE
analyzer: Correct balance of special addresses

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/oasis-indexer#261]
##### SUMMARY

Maintain the correct balance of special [reserved](https://docs.oasis.io/core/consensus/services/staking#reserved-addresses) accounts/addresses such as `oasis1qrmufhkkyyf79s5za2r8yga9gnk4t446dcy3a5zm`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Analyzer

##### ADDITIONAL INFORMATION

Relates to #123 
https://app.clickup.com/t/863frdmb0

**Comment by mitjat** [comment]
Resolved by #188
