### ISSUE TITLE
Add endpoint to fetch Emerald tx by hash

### ISSUE THREAD

**Issue by mitjat** [oasisprotocol/oasis-indexer#264]
URL: `/emerald/transactions/{tx_hash}`, analogous to what [consensus has](https://github.com/oasisprotocol/oasis-indexer/blob/3d9514fa6a2b7599c59689e6d736dd1fab24cc31/api/spec/v1.yaml#L282)

The backend should match on both kinds of hashes: "oasis" hash and eth hash.

**Comment by csillag** [comment]
Thanks for adding this! (Just tagging this issue for myself for easier tracking.)
