### ISSUE TITLE
Paratime Support

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/oasis-indexer#29]
**What is the problem that you're trying to solve?**
The wallet [extension](https://github.com/oasisprotocol/oasis-wallet-ext) migration to indexer API requires accessing paratime data.

**Describe the solution you'd like**
Implement the other paratime analyzers.

**Additional context**
Probably more needed here.

**Comment by mitjat** [comment]
First steps done :+1:, more features to add. Will be tracked elsewhere.
