### ISSUE TITLE
sender_0_eth doesn't check AddressPreimage context before converting oasis1 address

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-indexer#365]
##### ISSUE TYPE
- Bug Report

##### STEPS TO REPRODUCE

Transaction endpoint returns `sender_0_eth` for `consensus.Deposit` transactions

https://index-staging.oasislabs.com/v1/emerald/transactions/2b1a30eb672c4dbec92804b8144f3675c2ebc22d3c3993ca1513274fdf0a1cbe
```json
 "sender_0": "oasis1qzypxmt5xg8039329zvre7hxe7kn0vxfugsknqtw",
 "sender_0_eth": "0xa8E1A15b898df5B6807F034f7160cd6B8018937C",
```

but it looks like that account has a consensus staking context:

https://index-staging.oasislabs.com/v1/emerald/accounts/oasis1qzypxmt5xg8039329zvre7hxe7kn0vxfugsknqtw
```json
  "address": "oasis1qzypxmt5xg8039329zvre7hxe7kn0vxfugsknqtw",
  "address_preimage": {
    "address_data": "HBex6gIKmPD/qJoyqOGhW4mN9baAfwNPcWDNa4AYk3w=",
    "context": "oasis-core/address: staking",
    "context_version": 0
  },
```

**Comment by pro-wh** [comment]
yo mind if I take over this

**Comment by pro-wh** [comment]
#368 should fix this
