### ISSUE TITLE
Indexer api data is not updated.

### ISSUE THREAD

**Issue by yerycs** [oasisprotocol/oasis-indexer#386]
Indexer api data is not responding latest data.

`curl --location --request GET 'http://index.oasislabs.com/v1/consensus/accounts/oasis1qqs6ylpfurhf6gc9mw232fkmrt3d0673lyzc5xf2'`

Nonce of this account is 89 in indexer response.
But real nonce value is 139 in [oasisscan.com](https://www.oasisscan.com/accounts/detail/oasis1qqs6ylpfurhf6gc9mw232fkmrt3d0673lyzc5xf2)

Indexer api should return latest data.

**Comment by pro-wh** [comment]
https://index.oasislabs.com/v1/ it says it has only scanned up to block 4001552
