### ISSUE TITLE
api: Parity with `oasis-scan` and `oasis-monitor`

### ISSUE THREAD

**Issue by ennsharma** [oasisprotocol/oasis-indexer#46]
##### SUMMARY
We should support endpoints that we currently do not that offer functionality of Oasis Scan and Oasis Monitor, for ease of migration by apps that currently use one/both, such as the Oasis Wallet.

**Comment by aefhm** [comment]
I also don't see `logotype` in the Validator media based on this [spec](https://github.com/oasisprotocol/metadata-registry/blob/production/docs/adr/0001-entity-metadata.md).

**Comment by lukaw3d** [comment]
Not the nicest, but it could be queried from `keybase` field https://keybase.io/_/api/1.0/user/lookup.json?usernames=chorusoneinc

in oasisscan: https://github.com/bitcat365/oasisscan-backend/blob/9b84dc/src/main/java/romever/scan/oasisscan/service/ScanValidatorService.java#L305-L308
