### ISSUE TITLE
analyzer: Prepare SQL queries

### ISSUE THREAD

**Issue by ennsharma** [oasisprotocol/oasis-indexer#61]
##### SUMMARY
Rather than build SQL queries inline, we should factor them out to live in a single, easily auditable location. Related: #40 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`analyzer`

**Comment by aefhm** [comment]
[Example](https://github.com/oasisprotocol/oasis-indexer/blob/3419115dff474cba1ec88e37feb3cd96cbb7c8c0/api/v1/client.go#L42) of injection vulnerability found by @lukaw3d
