### ISSUE TITLE
Rethink oasis-node access

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-indexer#71]
The current intended way of accessing oasis-node 100% does not support archive nodes, for the same reason why https://github.com/oasisprotocol/emerald-web3-gateway/issues/286 exists.

Before this hits production this should be rethought and re-evaluated as this likely impacts storage strategy (while oasis-node is the best at storing oasis-node's data, when you can't connect to multiple versions of oasis-node simultaniously reliably, other options need to be considered).

**Comment by mitjat** [comment]
The current thinking is still that the current approach will work out OK. Each analyzer (probably instantiated in a separate k8s deployment, though not technically necessary) will connect to a separate node (oasis-3, oasis-4, etc) and write to a separate set of tables (namescoped by chain id) in the DB. How both sets of tables are merged is up for debate; my early bet is on a one-time migration of the oasis-3 content to the oasis-4 schema during the node upgrade window. But that's a larger question and is to be fully addressed in scope of #161 .
