### ISSUE TITLE
api: Losing precision in JSON

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-indexer#85]
#### What

https://index.oasislabs.com/v1/consensus/accounts/oasis1qz0ea28d8p4xk8xztems60wq22f9pm2yyyd82tmt returns
```js
{
    "address": "oasis1qz0ea28d8p4xk8xztems60wq22f9pm2yyyd82tmt",
    "nonce": 26,
    "available": 458433997081289,
    "escrow": 218143027902957902,
    "debonding": 169116656872914,
    "total": 218770578556912105
}
```

but it is JSON.parsed into
```js
{
    "address": "oasis1qz0ea28d8p4xk8xztems60wq22f9pm2yyyd82tmt",
    "nonce": 26,
    "available": 458433997081289,
    "escrow": 218143027902957900,  // !!
    "debonding": 169116656872914,
    "total": 218770578556912100  // !!
}
```

#### Fix

We agreed to present numbers as strings.

**Comment by lukaw3d** [comment]
Is there any established solution for this in most other chains?

**Comment by aefhm** [comment]
[Etherscan](https://etherscan.io/address/0x00000000219ab540356cbb839cbe05303d7705fa) appears to defer to server side rendering.
[Avalanche](https://snowtrace.io/address/0x029155f80f8093a196c399dde4e194ec5ab43c24) uses server side rendering.
[Cosmo](https://www.mintscan.io/cosmos/account/cosmos156gqf9837u7d4c4678yt3rl4ls9c5vuuxyhkw6) appears to just return the number.
[Algorand](https://github.com/algorand/indexer/blob/54d39d7801ca8bfa63717cf435739ab549668ca9/api/generated/common/types.go#L17) has a number.
[Polkadot on Subscan](https://polkadot.subscan.io/account/1qnJN7FViy3HZaxZK9tGAA71zxHSBeUweirKqCaox4t8GT7)'s uses strings.
[Atom](https://atomscan.com/accounts/cosmos1lpjekr8wnz93ea0p8rr6cn436jg2h5ttz4yzeu) does return a string.

I guess it is a matter of which format we want? The loss happens on `JSON.parse`, so we could technically use an alternative [parser](https://github.com/josdejong/lossless-json) and get around this?
```
textResponse = await (await fetch("https://index.oasislabs.com/v1/consensus/accounts/oasis1qz0ea28d8p4xk8xztems60wq22f9pm2yyyd82tmt")).text();
LosslessJSON.parse(textResponse);
```

I do see that Oasisscan uses strings [here](https://github.com/oasisprotocol/oasis-wallet-web/blob/bea9e2291032e77afd1709f1f197dda27b4a7e0e/src/vendors/oasisscan/swagger3.yml#L292), so perhaps we should just maintain consistency.

**Comment by lukaw3d** [comment]
Looks like Etherscan API also uses strings https://docs.etherscan.io/api-endpoints/accounts
```json
{
  "status":"1",
  "message":"OK",
  "result":[
      {
        "account":"0xddbd2b932c763ba5b1b7ae3b362eac3e8d40121a",
        "balance":"40891626854930000000000"
      },
      {
        "account":"0x63a9975ba31b0b9626b34300f7f627147df1f526",
        "balance":"332567136222827062478"
      },
```

and Cosmos
```sh
curl 'https://lcd-cosmos.cosmostation.io/cosmos/bank/v1beta1/balances/cosmos156gqf9837u7d4c4678yt3rl4ls9c5vuuxyhkw6?pagination.limit=1000' \
  -H 'Referer: https://www.mintscan.io/'
```
```json
{
  "balances": [
    {
      "denom": "uatom",
      "amount": "97183"
    }
  ],
```

**Comment by lukaw3d** [comment]
> we could technically use an alternative [parser](https://github.com/josdejong/lossless-json) and get around this?

Yeah; though there would be no warnings on incorrect usage, e.g. 
`curl 'https://index.oasislabs.com/v1/consensus/accounts/oasis1qz0ea28d8p4xk8xztems60wq22f9pm2yyyd82tmt' | jq .escrow`

> I do see that Oasisscan uses strings [here](https://github.com/oasisprotocol/oasis-wallet-web/blob/bea9e2291032e77afd1709f1f197dda27b4a7e0e/src/vendors/oasisscan/swagger3.yml#L292), so perhaps we should just maintain consistency.

We probably want strings in base units tho, so not really consistent

**Comment by aefhm** [comment]
> Yeah; though there would be no warnings on incorrect usage, e.g.
curl 'https://index.oasislabs.com/v1/consensus/accounts/oasis1qz0ea28d8p4xk8xztems60wq22f9pm2yyyd82tmt' | jq .escrow

Fair. That's a common enough path.

**Comment by aefhm** [comment]
> We probably want strings in base units tho, so not really consistent
Yeah, less of a problem with non base units.

**Comment by aefhm** [comment]
Oof, okay, I guess I lean towards string too now. cc @ennsharma if you wanted to vote on this

**Comment by ennsharma** [comment]
I vote strings :)

**Comment by aefhm** [comment]
@pro-wh heads up, when implemented, this change will convert numbers to their string representation.

**Comment by aefhm** [comment]
We can leave our numerics and bigints in the analyzer/backend, but API will present all numbers (effectively) as strings.

**Comment by mitjat** [comment]
https://app.clickup.com/t/3zy75n6
