### ISSUE TITLE
API instability

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-indexer#86]
debonding_delegations throws storage error for some accounts

Largest validators:
- https://index.oasislabs.com/v1/consensus/accounts/oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm/debonding_delegations
`{"msg":"internal storage error"}`

- https://index.oasislabs.com/v1/consensus/accounts/oasis1qq3xrq0urs8qcffhvmhfhz4p0mu7ewc8rscnlwxe/debonding_delegations
{"debonding_delegations":null} :heavy_check_mark: 

- https://index.oasislabs.com/v1/consensus/accounts/oasis1qpn83e8hm3gdhvpfv66xj3qsetkj3ulmkugmmxn3/debonding_delegations
{"debonding_delegations":null} :heavy_check_mark: 

- https://index.oasislabs.com/v1/consensus/accounts/oasis1qz0ea28d8p4xk8xztems60wq22f9pm2yyyd82tmt/debonding_delegations
`{"msg":"internal storage error"}`

- https://index.oasislabs.com/v1/consensus/accounts/oasis1qzv2rktycpcykhudyvg5l6u75v08lpfcw5nt7aj5/debonding_delegations
`{"msg":"internal storage error"}`

**Comment by lukaw3d** [comment]
Hm, also sometimes in delegations:
https://index.oasislabs.com/v1/consensus/accounts/oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90/delegations
`{"msg":"internal storage error"}`

**Comment by aefhm** [comment]
https://index.oasislabs.com/v1/consensus/epochs is also erroring

**Comment by lukaw3d** [comment]
https://index.oasislabs.com/v1/consensus/transactions?sender=oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90
is timeouting  Error 524

**Comment by aefhm** [comment]
Technically, we will need a redeploy and a re-index to clean up bad data. That should be batched with other changes.

**Comment by aefhm** [comment]
Redeployed and re-indexed. The above endpoints work for me.

**Comment by lukaw3d** [comment]
Seems like lots broke again now that indexer caught up :/

**Comment by aefhm** [comment]
> https://index.oasislabs.com/v1/consensus/transactions?sender=oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90 is timeouting Error 524

Let's address in https://github.com/oasisprotocol/oasis-indexer/issues/118

**Comment by aefhm** [comment]
Indexer has caught up. The above 5 endpoints work for me.

- [ ] [oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm](https://index.oasislabs.com/v1/consensus/accounts/oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm/debonding_delegations)
- [ ] [oasis1qq3xrq0urs8qcffhvmhfhz4p0mu7ewc8rscnlwxe](https://index.oasislabs.com/v1/consensus/accounts/oasis1qq3xrq0urs8qcffhvmhfhz4p0mu7ewc8rscnlwxe/debonding_delegations)
- [ ]  [oasis1qpn83e8hm3gdhvpfv66xj3qsetkj3ulmkugmmxn3](https://index.oasislabs.com/v1/consensus/accounts/oasis1qpn83e8hm3gdhvpfv66xj3qsetkj3ulmkugmmxn3/debonding_delegations)
- [ ]  [oasis1qz0ea28d8p4xk8xztems60wq22f9pm2yyyd82tmt](https://index.oasislabs.com/v1/consensus/accounts/oasis1qz0ea28d8p4xk8xztems60wq22f9pm2yyyd82tmt/debonding_delegations)
- [ ] [oasis1qzv2rktycpcykhudyvg5l6u75v08lpfcw5nt7aj5](https://index.oasislabs.com/v1/consensus/accounts/oasis1qzv2rktycpcykhudyvg5l6u75v08lpfcw5nt7aj5/debonding_delegations)

**Comment by lukaw3d** [comment]
https://index.oasislabs.com/v1/consensus/accounts/oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm/debonding_delegations looks like it has duplicated data:
```json
    {
      "amount": 4337851,
      "shares": 4337851,
      "address": "oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm",
      "debond_end": 14177
    },
    {
      "amount": 4337851879065922,
      "shares": 4337851879065922,
      "address": "oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm",
      "debond_end": 14177
    }
```

but others look okay

**Comment by lukaw3d** [comment]
oh, looks like that is accurate - there were two reclaim txs

**Comment by lukaw3d** [comment]
> https://index.oasislabs.com/v1/consensus/transactions?sender=oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90 is timeouting Error 524

moved into https://github.com/oasisprotocol/oasis-indexer/issues/121
