### ISSUE TITLE
Incorrect results for the validators query

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-indexer#92]
`wget https://index.oasislabs.com/v1/consensus/validators\?height\=9491840\&limit\=200` returns a 115 element array.  There are more than 115 validators.

Without the limit argument, 100 validators are returned (because that's not annoying at all), which also does not correspond to the top 100 validators.

Being able to query the current validator set is presumably a useful and common operation, so this query not returning results that reflect reality, is probably a big problem.

Note: It occurs to me that this may partially have to do with how oasisscan displays this information vs the indexer (I assume oasisscan's data is stale), but since I am getting truncated data I am inclined to believe that something is also badly busted.

**Comment by aefhm** [comment]
`?height` param is not available yet...

Currently (post-deploy), the default query set at max limit of `1000` returns all known entities with a `validator` roled `node` which at (still processing) height of `8328899` is `133` of which `120` are `active`.

**Comment by Yawning** [comment]
> ?height param is not available yet...

:(

**Comment by aefhm** [comment]
Closing. `height` param goes into https://github.com/oasisprotocol/oasis-indexer/issues/116
