### ISSUE TITLE
consider moving to cobra v1.5.0

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-indexer#99]
as of cobra v1.4.0, viper dependency is removed, which supposedly transitively pulls in a lot of other stuff.  updating would reduce the potential attack surface.

https://github.com/oasisprotocol/oasis-indexer/blob/5b0b5a7888df3e6db1ecae9485c2f00285af46ab/go.mod#L17

**Comment by aefhm** [comment]
Done via #105 although unfortunately `viper` is still a dependency of `oasis-core`.

**Comment by aefhm** [comment]
Closing unless we want to hold this issue specifically for `viper`?
